services:
  frontend:
    container_name: contract-frontend
    image: contract-frontend-v1
    ports:
      - "3000:3000"

  backend:
    container_name: contract-backend
    image: contract-backend-v1
    ports:
      - "8000:8000"
    depends_on:
      - frontend