
SOW_TEMPLATES:
  currency:
    - "INR"
    - "Total project compensation"
    - "Rate per SKU for"
    - "Commercials"
    - "Rate"
    - "USD per FTE per hour"
    - "Pricing is fixed"
    - "All applicable taxes"
    - "Rate per FTE"
    - "interest at a rate"
    - "FTE / Month"
    - "invoice process or format"
    - "usd"
  sow_no:
    - "SOW Number"
    - "SOW Reference"
    - "SOW no."
    - "Agreement Number"
    - "Amendment Number"
    - "Master Services Agreement date"
    - "Agreement effective date"
  sow_start_date:
    - "Effective Date"
    - "Start Date"
    - "commence on"
    - "Agreement shall commence on"
    - "This Agreement is entered on"
    - "This amendment will be effective"
    - "dated"
    - "effective as on"
    - "Start of Process Training"
    - "project has now been extended"
    - "is effective from"
    - "This amendment is effective from"
  remark:
    - "Comments"
    - "Additional Notes"
    - "Deliverables"
    - "Remark"
    - "SLAs"
    - "Except as expressly amended"
    - "feedback on the outcome"
    - "all other terms and conditions"
    - "SOP, checklist"
    - "performance dashboard"
  inclusive_or_exclusive_gst:
    - "Exclusive of GST"
    - "Inclusive of GST"
    - "GST applicable"
    - "All applicable taxes like GST"
  subcontract_clause:
    - "Subcontracting"
    - "Subcontract Clause"
    - "Third Party Subcontracting invoices"
    - "Service Provider shall not subcontract"
  sow_value:
    - "Total project compensation"
    - "Rate per SKU"
    - "Commercials"
    - "Total SOW Value"
    - "Pricing is fixed for the scope of work"
    - "Existing rate shall prevail"
    - "Volume fluctuations"
    - "YOY increase"
  credit_period:
    - "Payment Terms"
    - "Credit period"
    - "Payment to be finalized after"
    - "Payment of the invoice"
    - "Invoice will be raised"
    - "payment to be made within 30 days"
    - "interest at a rate"
  cola:
    - "Cost of Living Adjustment"
    - "COLA percentage"
    - "Year-on-Year increase for Cost of Living Adjustment"
    - "YOY increase for Cost-of-Living Adjustment"
    - "COLA at 8% per annum"
  total_fte:
    - "FTE"
    - "Rate per FTE"
    - "Total FTE required"
    - "personnel designated"
    - "Annotators"
    - "Team Lead"
    - "Headcount increase"
    - "per FTE per hour"
  client_company_name:
    - "by and between"
    - "party of the first part"
    - "party of the second part"
    - "entered into by"
    - "entered into between"
    - "this agreement is made between"
    - "agreement between"
    - "contract between"
    - "by and among"
    - "the company"
    - "the corporation"
    - "executed by"
    - "executed on behalf of"
    - "signed between"
  sow_end_date:
    - "end date"
    - "valid date"
    - "termination date"
    - "expiry date"
    - "contract end date"
    - "agreement ends on"
    - "will end on"
    - "expires on"
    - "1 year until"
  type_of_billing:
    - "payment terms"
    - "per FTE per month"
    - "purpose of billing"
    - "FEES AND PAYMENT"
    - "per FTE per hr"
  po_number:
    - "purchase order"
    - "change purchase order"
    - "ordered date"
    - "ordered by"
  amendment_no:
    - "amendment"
    - "to the consulting"

  billing_unit_type_and_rate_cost:
    - "The current rate per FTE"
    - "rate effective from"
    - "FTE/Month"
    - "Inclusive of GST."
    - "rate per hour"
    - "rate per FTE per hr"
    - "current rate per FTE"
    - "unit rate"
    - "Rate/hr"
    - "USD per FTE"
    - "INR per hr"
    - "existing rate valid till"
    - "amended rate effective from"

  particular_role_rate:
    - "Associate"
    - "Senior Associate"
    - "The current rate per FTE"
    - "rate effective from"
    - "FTE/Month"
    - "Inclusive of GST."
    - "rate per FTE per hr"
    - "current rate per FTE"
    - "unit rate"
    - "Rate/hr"
    - "USD per FTE"
    - "INR per FTE"
    - "existing rate valid till"

SOW_PROMPTS:
  currency: |
    Extract the currency from the following text:

    {page_content}

    Return only the currency mentioned in the document (e.g., 'INR', 'USD'). No additional text or explanations. If no currency is found, return 'NA'.
  
  sow_no: |
    Extract the SOW number from the following text:

    {page_content}

    Return only the SOW number or reference. No additional text or explanations. If no SOW number is found, return 'NA'.
  
  sow_start_date: |
    Extract the SOW start date from the following text:

    {page_content}

    Return only the start date in DD-MM-YYYY format. No additional text or explanations. If no start date is found, return 'NA'.
  
  remark: |
    Extract the remark from the following text:

    {page_content}

    Return only the remark or additional notes. No additional text or explanations. If no remark is found, return 'NA'.
  
  inclusive_or_exclusive_gst: |
    Extract the GST details from the following text:

    {page_content}

    Return whether GST is inclusive or exclusive. No additional text or explanations. If no GST details are found, return 'NA'.
  
  subcontract_clause: |
    Extract the subcontract clause from the following text:

    {page_content}

    Return only the subcontract clause details. No additional text or explanations. If no subcontract clause is found, return 'NA'.
  
  sow_value: |
    Extract the SOW value from the following text:

    {page_content}

    Return only the SOW value in the format of numbers followed by currency. No additional text or explanations. If no SOW value is found, return 'NA'.
  
  credit_period: |
    Extract the credit period from the following text:

    {page_content}

    Return only the credit period in number of days. No additional text or explanations. If no credit period is found, return 'NA'.
  
  cola: |
    Extract the COLA from the following text:

    {page_content}

    Return only the COLA details. If no COLA is found, return 'NA'. Return only the numerical value without any additional text or explanations.
  
  total_fte: |
    Extract the total FTE from the following text:

    {page_content}

    Return the total FTE as a numerical value. No additional text or explanations. If no total FTE is found, return 'NA'.
  
  client_company_name: |
    Extract the client company name from the following text:

    {page_content}

    Return only the client company name. If no client company name is found, return 'NA'.
  
  sow_end_date: |
    Extract the end date from the following text:

    {page_content}

    Return only the end date in DD-MM-YYYY format. If no end date is found, return 'NA'.
  
  type_of_billing: |
    Extract the type of billing from the following text:

    {page_content}

    Return only the type of billing. If no type of billing is found, return 'NA'. The types of billing are 'FTE Based' and 'Task Based'. Return only the words without any explanations.
  
  po_number: |
    Extract the PO number from the following text:

    {page_content}

    Return only the PO number. If no PO number is found, return 'NA'.
  
  amendment_no: |
    Extract the amendment number from the following text:

    {page_content}

    Return only the amendment number. If no amendment number is found, return 'NA'.

  billing_unit_type_and_rate_cost: |
    What is the unit type mentioned for billing in this contract? Look for terms like 'per FTE', 'per bag', 'per transaction' or per something along with cost associated with it.
    Extract the billing unit type and rate cost from the following text:

    {page_content}

    If there are more than one unit type and cost or rate, then return the in the following manner: 'per sample - 1000, per item - 5000', etc.Return the billing unit type and rate cost. If no billing unit type and rate cost is found, return 'NA'.

    <Importan> Do not include additional text or explanations in the output. Just return the billing unit type and rate cost if exist or 'NA' if not found. </Important>

  particular_role_rate: |
    Extract the rate for the particular role mentioned in the contract. The rate is the value mentioned after the word 'per'. If there are more than one rate, then return the in the following manner: 'Associate - 1000, Senior Associate - 5000', etc.

    {page_content}

    Return the role and rate. If no rate for a particular role is found, return 'NA'.

    <Importan> Do not include additional text or explanations in the output. Just return the billing unit type and rate cost if exist or 'NA' if not found. </Important>