embedding_model_name: "BAAI/bge-large-en-v1.5"

fields_to_extract:
  - start_date
  - company_name
  - service_provider_name
  - end_date
  - company_address
  - service_provider_address
  - cola
  - no_of_fte
  - unit_rate
  - limitation_of_liability

queries_json:
  start_date:
    - "What is the effective start date of the agreement or contract?"

  company_name:
    - "What is the name of the company or legal entity that is party to this contract?"

  service_provider_name:
    - "What is the name of the service provider or vendor mentioned in the contract?"

  end_date:
    - "What is the termination or end date of the contract?"

  company_address:
    - "What is the official address of the company mentioned in this contract?"

  service_provider_address:
    - "What is the official address of the service provider or vendor mentioned in this contract?"

  cola:
    - "What is the cost of living adjustment (COLA) mentioned in the contract?"

  no_of_fte:
    - "How many Full-Time Equivalents (FTE) are mentioned in this contract?"

  unit_rate:
    - "What is the unit rate for services mentioned in this contract?"

  limitation_of_liability:
    - "What is the limitation of liability clause mentioned in this contract?"

prompt_template: |
  You are an AI assistant specializing in extracting specific fields from business contracts. 
  Your task is to retrieve the requested field value from the provided contract content.

  Context:
  - The documents you are analyzing are legally binding contracts between businesses or entities.
  - Fields you are tasked with extracting include key contract details such as dates, company names, terms, parties involved, and other important business information.
  - Your role is to accurately extract these values without any assumptions or additional commentary.

  Instructions:
  1. Based on the provided field name and the relevant contract content, extract the value for the specified field in the following format:
  {{ "value": "[Extracted value]", "field_value_found": true }} if the value is found.
  2. If the value is not present in the provided content or cannot be determined, return:
  {{ "value": "null", "field_value_found": false }}.
  3. Return the output in plain text, not as a code cell or in markdown.
  4. Do not hallucinate or invent any information. If the content does not contain the answer, return "null" as the value.
  5. Ensure your response is based only on the provided contract content and related field.
  6. Return the output only in the JSON format described above, with no additional text or explanations.

  Required Field: {required_field}
  Relevant Contract Content: {similar_content}

  Return only the value in the strict JSON format.