embedding_model_name: "Alibaba-NLP/gte-large-en-v1.5"

fields_to_extract:
  - currency
  - sow_no
  - sow_start_date
  - sow_end_date
  - sow_value
  - credit_period
  - cola
  - total_fte

queries_json:
  currency:
    - "What is the currency mentioned in the contract?"

  sow_no:
    - "What is the Statement of Work (SOW) number mentioned in the contract?"

  sow_start_date:
    - "What is the start date of the Statement of Work (SOW)?"

  sow_end_date:
    - "What is the end date of the Statement of Work (SOW)?"

  sow_value:
    - "What is the value of the Statement of Work (SOW) mentioned in the contract?"

  credit_period:
    - "What is the credit period mentioned in the contract?"
    - "What is the payment cycle?"
    - "Payment deadline"

  cola:
    - "What is the cost of living adjustment (COLA) mentioned in the contract?"

  total_fte:
    - "What is the total number of Full-Time Equivalents (FTE) mentioned in the contract?"
    - "What is the number of employees assigned?"

prompt_template: |
  You are an AI assistant specializing in extracting specific fields from business contracts. 
  Your task is to retrieve the requested field value from the provided contract content.

  Context:
  - The documents you are analyzing are legally binding contracts between businesses or entities.
  - Fields you are tasked with extracting include key contract details such as dates, company names, terms, parties involved, and other important business information.
  - Your role is to accurately extract these values without any assumptions or additional commentary.

  Instructions:
  1. Before doing anything, you MUST think step by step like so:
  <steps>
  Step 1:
  <your thoughts>
  
  Step2:
  <your thoughts>
  ...
  </steps>
  
  And then based on the provided field name and the relevant contract content, extract the value for the specified field like so:
  
  <extracted>
  {{ "value": "[Extracted value]", "field_value_found": true }} if the value is found.
  </extracted>
  
  2. Overall, this SHOULD be your OUTPUT FORMAT:
  
  <steps>
  Step 1:
  <your thoughts>
  
  Step2:
  <your thoughts>
  ...
  </steps>
  
  <extracted>
  {{ "value": "[Extracted value]", "field_value_found": true }} if the value is found.
  </extracted>
  
  3. If the value is not present in the provided content or cannot be determined, return:
  {{ "value": "null", "field_value_found": false }}.
  4. Return the output in plain text, not as a code cell or in markdown.
  5. Do not hallucinate or invent any information. If the content does not contain the answer, return "null" as the value.
  6. Ensure your response is based only on the provided contract content and related field.
  7. Return the output ONLY in the format described above.

  Required Field: {required_field}
  Relevant Contract Content: {similar_content}

  The output should be in the provided format ONLY.