embedding_model_name: "Alibaba-NLP/gte-large-en-v1.5"

sow_fields_to_extract:
  - client_company_name
  - currency
  - sow_start_date
  - sow_end_date
  - cola
  - credit_period
  - inclusive_or_exclusive_gst
  - sow_value
  - sow_no
  
sow_queries:
  client_company_name:
    - "What is the name of the recipient company? Next Wealth is the service provide name so extract the recipient company name."

  currency:
    - "Dummy Text This is"
    - "What is the currency mentioned in the contract?Is the currency is in USD($) OR INR(₹)?"

  sow_start_date:
    - "What is the start date of the Statement of Work (SOW)?"

  sow_end_date:
    - "What is the end date of the Statement of Work (SOW)?"
    
  cola:
    - "What is the cost of living adjustment (COLA) mentioned in the contract?"

  credit_period:
    - "Invoice will be raised on the last day of the month and the payment to be made net 45 days of receiving invoice."
    - "Credit period is 45 days from the date of invoice. What is the credit period mentioned in the contract?"

  inclusive_or_exclusive_gst:
    - "What are the terms regarding the inclusion or exclusion of GST in the pricing structure, as detailed in the amendment or Statement of Work (SOW)?"
    - "Can you identify any clauses in the amendment or SOW that specify whether applicable taxes, including GST, are included or excluded in the quoted service rates?"
    - "Does the document clarify if the fees or charges mentioned are inclusive or exclusive of GST? Look for relevant sections in the SOW or amendment."

  sow_value:
    - "Can you extract the total monetary value or sow value specified for the services in the contract's Statement of Work (SOW) or any amendments?"
    - "What is the final contract value as described in the SOW, including adjustments, if applicable, in the amendments?"
    - "What is the total value of the Statement of Work (SOW), including all relevant costs or services, as outlined in the contract and amendments?"

  sow_no:
    - "What is the Statement of Work (SOW) number mentioned in the document? Identify the unique identifier for the SOW, often found in the title or first section of the contract."
    - "Extract the Statement of Work Number (SOW No.) associated with the agreement or amendment, usually found at the beginning of the document."
    - "In which section is the Statement of Work number (SOW No.) mentioned? It's typically present in the opening paragraph or title of the agreement."

prompt_template: |
  You are an AI assistant specializing in extracting specific fields from business contracts. 
  Your task is to retrieve the requested field value from the provided contract content.

  Context:
  - The documents you are analyzing are legally binding contracts between businesses or entities.
  - Fields you are tasked with extracting include key contract details such as dates, company names, terms, parties involved, and other important business information.
  - Your role is to accurately extract these values without any assumptions or additional commentary.

  Instructions:
  1. Before doing anything, you MUST think step by step like so:
  <steps>
  Step 1:
  <your thoughts>
  
  Step2:
  <your thoughts>
  ...
  </steps>
  
  And then based on the provided field name and the relevant contract content, extract the value for the specified field like so:
  
  <extracted>
  {{ "value": "[Extracted value]", "field_value_found": true }} if the value is found.
  </extracted>
  
  2. Overall, this SHOULD be your OUTPUT FORMAT:
  
  <steps>
  Step 1:
  <your thoughts>
  
  Step2:
  <your thoughts>
  ...
  </steps>
  
  <extracted>
  {{ "value": "[Extracted value]", "field_value_found": true }} if the value is found.
  </extracted>
  
  3. If the value is not present in the provided content or cannot be determined, return:
  {{ "value": "null", "field_value_found": false }}.  
  5. Return the output in plain text, not as a code cell or in markdown.
  6. Do not hallucinate or invent any information. If the content does not contain the answer, return "null" as the value.
  7. Ensure your response is based only on the provided contract content and related field.
  8. Return the output ONLY in the format described above.

  Required Field: {required_field}
  Relevant Contract Content: {similar_content}

  The output should be in the provided format ONLY.