templates:
  start_date:
    - "amendment will be effective September 1, 2023"
    - "effective from July 15, 2023"
    - "rate effective from September 1, 2023"
    - "agreement shall commence from"
    - "starts on"
    - "will be effective"
    - "effective date"
    - "commencement date"
    - "effective from"
    - "beginning on"
    - "valid from"
    - "entered into"

  company_names:
    - "by and between"
    - "party of the first part"
    - "party of the second part"
    - "entered into by"
    - "entered into between"
    - "this agreement is made between"
    - "agreement between"
    - "contract between"
    - "by and among"
    - "the company"
    - "the corporation"
    - "executed by"
    - "executed on behalf of"
    - "signed between"

  service_provider_name:
    - "service provider"
    - "the provider"
    - "service agreement"
    - "the provider will"
    - "provider will perform"

  end_date:
    - "end date"
    - "valid date"
    - "termination date"
    - "expiry date"
    - "contract end date"
    - "agreement ends on"
    - "will end on"
    - "expires on"
    - "1 year until"

  company_address:
    - "registered office at"
    - "principal place of business"
    - "address of the company"
    - "located at"
    - "headquarters at"
    - "corporate office at"
    - "office located at"
    - "having its office at"

  service_provider_address:
    - "registered office at"
    - "headquarters located at"
    - "principal office at"
    - "corporate office at"
    - "having its registered office at"

  cola:
    - "Cost of Living Adjustment"
    - "COLA"
    - "adjustment for inflation"
    - "inflation adjustment"
    - "cost-of-living increase"

  number_of_fte:
    - "deployed on account"
    - "number of FTE"
    - "current headcount"
    - "billable headcount"
    - "FTE deployed"
    - "total FTE"
    - "we will deploy"

  unit_rate:
    - "The current rate per FTE"
    - "rate effective from"
    - "/FTE/Month Inclusive of GST."
    - "rate per hour"
    - "rate per FTE per hr"
    - "current rate per FTE"
    - "unit rate"
    - "Rate/hr"
    - "USD per FTE"
    - "USD per hr"
    - "INR per FTE"
    - "INR per hr"
    - "existing rate valid till"
    - "amended rate effective from"

  limitation_of_liability:
    - "limitation of liability"
    - "aggregate liability"
    - "liability shall not exceed"
    - "shall not be liable beyond"
    - "liability is limited to"
    - "service fee paid or payable"
    - "damages of any nature"
    - "claims, losses, costs, damages"
    - "attorney’s fees"
    - "extent permitted by law"
    - "liability for any and all claims"
    - "liability or cause of action"